apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    name: prometheus-pv
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /prometheus
  persistentVolumeReclaimPolicy: Recycle

