apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-service
  name: prometheus-service
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30090
  selector:
    app: prometheus
